-- ============================================================================
-- Migration 034: reservation_tasks
-- ============================================================================
-- Source endpoint: GET /public/inventory/v1/reservation/{id}/tasks
--   "Retrieve tasks linked to reservation"
-- Self-contained link table (does NOT modify tasks / task_assignments).
-- Captures the authoritative reservation -> task mapping plus the assignment
-- and supply detail this endpoint uniquely returns. Scoped at ETL time to
-- reservations with 2026-onward check-in/checkout dates.
-- Date: 2026-06-23
-- ============================================================================

CREATE TABLE IF NOT EXISTS breezeway.reservation_tasks (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code           varchar(32)  NOT NULL,
    reservation_id        varchar(64)  NOT NULL,   -- Breezeway reservation id (the queried id)
    reservation_pk        bigint,                  -- soft FK -> breezeway.reservations.id (resolved)
    task_id               varchar(64)  NOT NULL,   -- Breezeway task id
    task_pk               bigint,                  -- soft FK -> breezeway.tasks.id (resolved)
    home_id               varchar(64),
    task_name             text,
    task_description      text,
    type_department       varchar(64),
    type_priority         varchar(64),
    task_status_code      varchar(64),
    task_status_name      text,
    task_status_stage     varchar(64),
    scheduled_date        date,
    scheduled_time        time without time zone,
    task_created_at       timestamptz,             -- task.created_at from API
    started_at            timestamptz,
    finished_at           timestamptz,
    paused                boolean,
    rate_type             varchar(64),
    rate_paid             numeric(15,2),           -- currency suffix stripped at load
    total_time            varchar(32),
    template_id           varchar(128),
    reference_property_id text,
    report_url            text,
    assignments           jsonb,                   -- raw assignments[] (assignee id/name/status)
    supplies              jsonb,                   -- raw supplies[]
    costs                 jsonb,                   -- raw costs[]
    tags                  jsonb,
    task_tags             jsonb,
    raw_payload           jsonb,                   -- full task object as returned
    synced_at             timestamptz DEFAULT now(),
    created_at            timestamptz DEFAULT now(),
    updated_at            timestamptz DEFAULT now(),
    CONSTRAINT uq_reservation_tasks UNIQUE (reservation_id, task_id, region_code)
);

CREATE INDEX IF NOT EXISTS idx_restasks_reservation_pk  ON breezeway.reservation_tasks (reservation_pk);
CREATE INDEX IF NOT EXISTS idx_restasks_task_pk         ON breezeway.reservation_tasks (task_pk);
CREATE INDEX IF NOT EXISTS idx_restasks_region          ON breezeway.reservation_tasks (region_code);
CREATE INDEX IF NOT EXISTS idx_restasks_reservation     ON breezeway.reservation_tasks (reservation_id, region_code);
CREATE INDEX IF NOT EXISTS idx_restasks_scheduled_date  ON breezeway.reservation_tasks (scheduled_date);
CREATE INDEX IF NOT EXISTS idx_restasks_department      ON breezeway.reservation_tasks (type_department);

-- Ownership + read access consistent with the rest of the schema (see migration 033)
ALTER TABLE breezeway.reservation_tasks OWNER TO breezeway;
GRANT SELECT ON breezeway.reservation_tasks TO ai_reader;

-- Verify
SELECT tablename, tableowner FROM pg_tables
WHERE schemaname = 'breezeway' AND tablename = 'reservation_tasks';
