-- 035: Breezeway reference entities — full public-endpoint coverage (2026-06-23)
-- Per-region (per-company) reference lists. Mirror the breezeway.tags structure:
-- surrogate id PK, (entity_id, region_code) unique, FK to breezeway.regions.
-- Owned by the breezeway ETL user; ai_reader gets SELECT.

CREATE TABLE IF NOT EXISTS breezeway.subdepartments (
    id                   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code          varchar NOT NULL REFERENCES breezeway.regions(region_code) ON DELETE CASCADE,
    subdepartment_id     varchar NOT NULL,
    subdepartment_name   varchar,
    reference_company_id varchar,
    last_sync_time       timestamptz,
    updated_at           timestamptz,
    created_at           timestamptz,
    synced_at            timestamptz,
    CONSTRAINT uq_subdepartments_natural_key UNIQUE (subdepartment_id, region_code)
);

CREATE TABLE IF NOT EXISTS breezeway.templates (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code     varchar NOT NULL REFERENCES breezeway.regions(region_code) ON DELETE CASCADE,
    template_id     varchar NOT NULL,
    template_name   varchar,
    department_code varchar,
    last_sync_time  timestamptz,
    updated_at      timestamptz,
    created_at      timestamptz,
    synced_at       timestamptz,
    CONSTRAINT uq_templates_natural_key UNIQUE (template_id, region_code)
);

CREATE TABLE IF NOT EXISTS breezeway.property_tags (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code     varchar NOT NULL REFERENCES breezeway.regions(region_code) ON DELETE CASCADE,
    property_tag_id varchar NOT NULL,
    tag_name        varchar,
    company_id      bigint,
    last_sync_time  timestamptz,
    updated_at      timestamptz,
    created_at      timestamptz,
    synced_at       timestamptz,
    CONSTRAINT uq_property_tags_natural_key UNIQUE (property_tag_id, region_code)
);

CREATE TABLE IF NOT EXISTS breezeway.reservation_tags (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code        varchar NOT NULL REFERENCES breezeway.regions(region_code) ON DELETE CASCADE,
    reservation_tag_id varchar NOT NULL,
    tag_name           varchar,
    company_id         bigint,
    last_sync_time     timestamptz,
    updated_at         timestamptz,
    created_at         timestamptz,
    synced_at          timestamptz,
    CONSTRAINT uq_reservation_tags_natural_key UNIQUE (reservation_tag_id, region_code)
);

ALTER TABLE breezeway.subdepartments   OWNER TO breezeway;
ALTER TABLE breezeway.templates        OWNER TO breezeway;
ALTER TABLE breezeway.property_tags    OWNER TO breezeway;
ALTER TABLE breezeway.reservation_tags OWNER TO breezeway;

GRANT SELECT ON breezeway.subdepartments, breezeway.templates,
                breezeway.property_tags, breezeway.reservation_tags TO ai_reader;
